### ISSUE TITLE
NoClassDefFoundError in v1.2.8

### ISSUE THREAD

**Issue by HirogaKatageri** [Giphy/giphy-android-sdk-ui-example#53]
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/giphy/sdk/ui/r;
       at com.giphy.sdk.ui.d.<init>(:30)
       at com.giphy.sdk.ui.c.<init>(:17)
       at com.giphy.sdk.ui.a.a(:45)
       at com.giphy.sdk.ui.l.a(:98)
       at com.giphy.sdk.ui.Giphy.configure(:22)
       at tv.nexusgaming.streaming.NexplayApplication.onCreate(NexplayApplication.kt:69)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1183)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6479)
       at android.app.ActivityThread.access$1300(ActivityThread.java:220)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7397)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by PiotrPrus** [comment]
This is a returning issue. I encounter it in `1.2.5`, they have fixed it in 1.2.6 and broke again in 1.2.8

**Comment by HirogaKatageri** [comment]
In 1.2.6 they also had a different [issue](https://github.com/Giphy/giphy-android-sdk-ui-example/issues/44), that's when I updated to 1.2.8 for our previous release. I skipped 1.2.7 there were no issues on our previous releases using 1.2.8 so I was surprised to encounter another issue like this.

**Comment by alexbagg03** [comment]
I am experiencing this issue on **v2.0.1**. Any resolution to this? 

Only workaround I have right now is to `Rebuild` the project in Android Studio anytime it occurs. After rebuilding, the crash does not occur initially but eventually comes up again leading me to believe the build cache used by the SDK gets into a bad state. Not sure if it only happens after I make changes to my app's code or some other way, but nonetheless it keeps reoccurring and is very annoying in development.

**Comment by Gazzx** [comment]
This problem is quite annoying, I have it on v2.0.3 and the only way to fix it is a rebuild which is not good in big projects that take minutes to rebuild.

it mostly happens when I change a big chunk in my code or on my first build the next day.

**Comment by dino9** [comment]
I've been thinking to get rid of the complete Giphy SDK as it seems to have some bundling issues. While building SDK it looks like obfuscated files are getting bundled.

**Comment by HirogaKatageri** [comment]
@dino9 I can confirm they have obfuscated files and its these files that are sometimes obfuscated that are causing issues.

**Comment by ALexanderLonsky** [comment]
@dino9, @HirogaKatageri I'll look into this.

**Comment by ALexanderLonsky** [comment]
@dino9, @HirogaKatageri, @Gazzx, @alexbagg03 

Actually it's weird and I can't even reproduce this on my side.

I've made a new rule for this one:`com/giphy/sdk/ui/r;`

Could you please check if that version works for you?
`com.giphy.sdk:ui:2.0.3-obfuscation-issue`

**Comment by ALexanderLonsky** [comment]
And one more question: do you use proguard for your debug builds?

**Comment by HirogaKatageri** [comment]
@ALexanderLonsky On our end, we haven't enabled proguard on both our debug and release builds yet.

**Comment by dino9** [comment]
@ALexanderLonsky The new obfuscation lib is not fixing the issue. I tried a couple of times but the same issue.

**Comment by ALexanderLonsky** [comment]
@HirogaKatageri I see, thank you.
@dino9 is it the same:
```
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/giphy/sdk/ui/r;
at com.giphy.sdk.ui.d.(:30)
at com.giphy.sdk.ui.c.(:17)
at com.giphy.sdk.ui.a.a(:45)
at com.giphy.sdk.ui.l.a(:98)
```
?

**Comment by ALexanderLonsky** [comment]
@dino9 here is a version without obfuscation:
`com.giphy.sdk:ui:2.0.3-no-obfuscation`

**Comment by dino9** [comment]
@ALexanderLonsky Yup. Got fixed. @HirogaKatageri How's from ur end?

**Comment by HirogaKatageri** [comment]
@ALexanderLonsky @dino9 It's working fine on my end.

**Comment by ALexanderLonsky** [comment]
@dino9 , @HirogaKatageri 
Could you please help me to reproduce the issue at my end using an obfuscated version?
do you have any sample project to share where this is happening?

does Giphy-Example project work for you?

what gradle version, android studio version do you use?
do use instant run in Android Studio or not? 
do you have any custom scripting in your gradle config?

Thanks in advance!
